`font` -> `family` in theme.fontFaces docs (#11427)
## Describe your changes

When I tried to follow the docs as-is, I got this error 

```
google.protobuf.json_format.ParseError: Message type "FontFace" has no field named "font" at "FontFace".
 Available Fields(except extensions): "['url', 'family', 'weight', 'style']"
 ```

Here was the config I was trying to use 

```toml
[theme]
font = "SF Mono"

[[theme.fontFaces]]
font = "SF Mono"
url = "app/static/SFMono-Heavy.otf"
weight = 400
style = "normal"
```
 
 So I tried `family` instead of `font`, and it worked

```toml
[theme]
font = "SF Mono"

[[theme.fontFaces]]
family = "SF Mono" # Changed font -> family
url = "app/static/SFMono-Heavy.otf"
weight = 400
style = "normal"
```

This was with streamlit 1.45.1

## GitHub Issue Link (if applicable)

## Testing Plan

- Explanation of why no additional tests are needed
- Unit Tests (JS and/or Python)
- E2E Tests
- Any manual testing needed?

---

**Contribution License Agreement**

By submitting this pull request you agree that all contributions to this project are made under the Apache 2.0 license.

---------

Co-authored-by: Debbie Matthews <debbie.matthews@snowflake.com>